### ISSUE TITLE
Improvements to make in this repository

### ISSUE THREAD

**Issue by choldgraf** [binder-examples/tensorboard#1]
In https://github.com/jupyterhub/binder/pull/181 we identified some improvements that should be made to this repository. This issue is a quick list so that we can work on them.

@btel it would be fantastic if you could give this a shot :-)

* Remove language that is for Bokeh (e.g. https://github.com/binder-examples/tensorboard/blob/master/tensorboardserverextension.py#L5)
* Update the README so that it is consistent with the other `binder-examples` repositories. E.g., that the headers are the same etc (see https://github.com/binder-examples/conda for example)

**Comment by btel** [comment]
Thanks! I am on it!

**Comment by btel** [comment]
ok, first try submitted. Have a look and let me know what you think. The notebook was taken and adapted from  tensorflow docs. It's licensed under apache 2.0. If there is a license incompatibility issue, I can replace the notebook with a different, self-made example.
